services:
  # backend:
  #   build: 
  #     context: ./backend
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - mongodb
  #   env_file:
  #     - ./backend/.env
  #   networks:
  #     - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: C0nversA

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 